#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML
# pages, let’s install one!

apt-get update
apt-get install -y nginx

mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart
