#!/usr/bin/env bash
# Configure HAproxy to send traffic to web-01 and web-02 using roundrobin
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 268057-web-01 100.25.117.101:80 check
    server 268057-web-02 54.160.106.191:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl start haproxy
sudo systemctl enable haproxy
