#!/usr/bin/env bash
# Fixes a Nginx server's innability to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
